name: Can be built successfully on ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install libudisks2-dev libxml2-dev python libpam0g-dev
    - name: make
      run: make
